# Docker Compose override file for self-hosted S3 (MinIO) configuration
# This file enables MinIO services when SELF_HOST_S3=true
# Usage: docker-compose -f docker-compose.yml -f docker-compose.s3.yml up

services:
  notesnook-s3:
    image: minio/minio:RELEASE.2024-07-29T22-14-52Z
    ports:
      - 9000:9000
    networks:
      - notesnook
    volumes:
      - s3data:/data/s3
    environment:
      MINIO_BROWSER: "on"
    env_file:
      - .env
      - env/domain.env
      - env/basic.env
      - env/smtp.env
      - env/twilio.env
      - env/servers.env
      - env/s3.env
      - env/traefik.env
      - env/webapp.env
    command: server /data/s3 --console-address :9090
    healthcheck:
      test: timeout 5s bash -c ':> /dev/tcp/127.0.0.1/9000' || exit 1
      interval: 40s
      timeout: 30s
      retries: 3
      start_period: 60s

  # There's no way to specify a default bucket in Minio so we have to
  # set it up ourselves.
  setup-s3:
    image: minio/mc:RELEASE.2024-07-26T13-08-44Z
    depends_on:
      - notesnook-s3
    networks:
      - notesnook
    entrypoint: /bin/bash
    env_file:
      - .env
      - env/domain.env
      - env/basic.env
      - env/smtp.env
      - env/twilio.env
      - env/servers.env
      - env/s3.env
      - env/traefik.env
      - env/webapp.env
    command:
      - -c
      - |
        until mc alias set minio http://notesnook-s3:9000 ${MINIO_ROOT_USER:-minioadmin} ${MINIO_ROOT_PASSWORD:-minioadmin}; do
          sleep 1;
        done;
        mc mb minio/attachments -p

volumes:
  s3data:
